import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import "./globals.css";
import "../styles/main.scss";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex justify-center">
          <div className="container">
            <div className="flex justify-center">
              <Link href="/" className="p-4">
                Home
              </Link>
              <Link href="/auth/register" className="p-4">
                registration
              </Link>
              <Link href="/choose-lang" className="p-4">
                Choose lang templ
              </Link>
              <Link href="/all-verbs" className="p-4">
                All verbs
              </Link>
            </div>
          </div>
        </div>

        {children}
      </body>
    </html>
  );
}
