import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import "./globals.css";
import "../styles/main.scss";
import "@/styles/main-menu.scss";
const inter = Inter({ subsets: ["latin"] });
import Providers from "./Providers";
import MainMenu from "@/components/MainMenu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="">
          <MainMenu />
        </div>
        <div className="pt-36">
          <Providers>{children}</Providers>
        </div>
      </body>
    </html>
  );
}
